services:
  db:
    image: pgvector/pgvector:pg16
    container_name: scriptengine-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mylocalpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
